### ISSUE TITLE
Swagger-Net is not compatible with System.ValueTuple 4.4.0

### ISSUE THREAD

**Issue by MartinZikmund** [heldersepu/Swagger-Net#48]
I have found out Swagger-Net is not compatible with System.ValueTuple 4.4.0 package. When I update from version 4.3.0 to 4.4.0 of this package, Swagger fails to load API definition. I am using the latest stable 8.3.13.2.

Following is the error message listing from the spec endpoint:

```
{
    "Message": "An error has occurred.",
    "ExceptionMessage": "The 'p' start tag on line 1241 position 2 does not match the end tag of 'th'. Line 1241, position 92.",
    "ExceptionType": "System.Xml.XmlException",
    "StackTrace": "  
        at System.Xml.XmlTextReaderImpl.Throw(Exception e)
        at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
        at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
        at System.Xml.XmlTextReaderImpl.ParseEndElement()
        at System.Xml.XmlTextReaderImpl.ParseElementContent()
        at System.Xml.XmlTextReaderImpl.Read()
        at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
        at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
        at Swagger.Net.Application.SwaggerDocsConfig.<>c__DisplayClass58_0.b__0()
        at Swagger.Net.Application.SwaggerDocsConfig.GetSwaggerProvider(HttpRequestMessage swaggerRequest)
        at Swagger.Net.Application.SwaggerDocsHandler.Generate(HttpRequestMessage request, String apiVersion)
        at Swagger.Net.Application.SwaggerDocsHandler.<>c__DisplayClass5_0.b__0(String _)
        at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
        at Swagger.Net.Application.SwaggerDocsHandler.GetContent(HttpRequestMessage request)
        at Swagger.Net.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        at Catalyst.WebApi.Infrastructure.LanguageMessageHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
        at Catalyst.WebApi.Infrastructure.LanguageMessageHandler.d__6.MoveNext() in C:\\Dev\\CatalystServer\\Catalyst.WebApi\\Infrastructure\\LanguageMessageHandler.cs:line 70
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Web.Http.HttpServer.d__24.MoveNext()
    "
}
```

**Comment by heldersepu** [comment]
Can you create a minimal project reproducing your issue?

**Comment by heldersepu** [comment]
Ignore my previous comment!
just adding the System.ValueTuple crashed my test project...
I think the problem is with my implementation of `IncludeAllXmlComments`

**Comment by heldersepu** [comment]
The XML on that project (System.ValueTuple.xml) is not valid they should fix it 
... but I was not accounting for that

**Comment by heldersepu** [comment]
Correction made and new package uploaded to Nuget:
https://www.nuget.org/packages/Swagger-Net/8.3.13.3

thanks for reporting the issue!
